//nolint:bodyclose
package oops

import (
	"fmt"
	"log/slog"
	"net/http"
	"runtime"
	"sync"
	"time"

	"github.com/samber/lo"
)

// Global configuration variables that control the behavior of error handling.
var (
	// SourceFragmentsHidden controls whether source code fragments are included in error output.
	// When true, source code context around error locations is hidden to reduce output size.
	SourceFragmentsHidden = true

	// DereferencePointers controls whether pointer values in error context are automatically
	// dereferenced when converting to map representations. This can be useful for logging
	// but may cause issues with nil pointers.
	DereferencePointers = true

	// Local specifies the timezone used for error timestamps. Defaults to UTC.
	Local *time.Location = time.UTC

	// AutoTraceID controls whether a ULID-based trace ID is automatically generated
	// when an error is created without an explicit trace.
	//
	// Note: this flag does not integrate with or take precedence over external tracing
	// systems (OpenTelemetry, HTTP middleware, etc.). Trace IDs from those systems must
	// still be injected explicitly via .Trace("id").
	//
	// Generating a trace ID on every error creation has a non-negligible cost (ULID
	// generation + allocation). Consider setting this to false at program start when
	// trace IDs are always provided by an external system.
	AutoTraceID = true
)

// Type assertions to ensure OopsError implements required interfaces.
var (
	_ error          = (*OopsError)(nil)
	_ slog.LogValuer = (*OopsError)(nil)
)

// OopsErrorLayer holds the attributes of a single layer in an error chain,
// as returned by Layers(). Every field reflects the value set at that specific
// wrapping level only — no chain traversal is performed. Fields that were not
// set on that layer carry their zero value.
type OopsErrorLayer struct {
	// Core error information
	Code     any
	Time     time.Time
	Duration time.Duration

	// Contextual information
	Domain  string
	Tags    []string
	Context map[string]any

	// Tracing information
	Trace string
	Span  string

	// Developer-facing information
	Hint   string
	Public string
	Owner  string

	// User and tenant information
	UserID     string
	UserData   map[string]any
	TenantID   string
	TenantData map[string]any

	// HTTP request/response information
	Request  *http.Request
	Response *http.Response
}

// outputBlock is one node in the error chain, holding pre-filtered frames.
type outputBlock struct {
	err    error
	msg    string
	frames []oopsStacktraceFrame
}

// OopsError represents an enhanced error with additional contextual information.
// It implements the standard error interface while providing rich metadata for
// debugging, logging, and error handling.
type OopsError struct {
	// Core error information
	err      error         // The underlying error being wrapped
	msg      string        // Additional error message
	code     any           // Machine-readable error code/slug (any JSON/log-friendly type)
	time     time.Time     // When the error occurred
	duration time.Duration // Duration associated with the error

	// Contextual information
	domain  string         // Feature category or domain (e.g., "auth", "database")
	tags    []string       // Tags for categorizing the error
	context map[string]any // Key-value pairs for additional context

	// Tracing information
	trace              string // Transaction/trace/correlation ID
	traceAutoGenerated bool   // true when trace was set by the library, false when set explicitly by the caller
	span               string // Current span identifier

	// Developer-facing information
	hint   string // Debugging hint for developers
	public string // User-safe error message
	owner  string // Team/person responsible for handling this error

	// User and tenant information
	userID     string         // User identifier
	userData   map[string]any // User-related data
	tenantID   string         // Tenant identifier
	tenantData map[string]any // Tenant-related data

	// HTTP request/response information
	req *lo.Tuple2[*http.Request, bool]  // HTTP request with body inclusion flag
	res *lo.Tuple2[*http.Response, bool] // HTTP response with body inclusion flag

	// Stack trace information
	stacktrace *oopsStacktrace // Captured stack trace
	callerSkip int             // Number of additional frames to skip when capturing stack trace

	// Lazily computed filtered frame blocks shared by Stacktrace() and Sources().
	// Both are pointers so that value copies of OopsError share the same state;
	// cacheOnce as a pointer also avoids the go vet copylocks check.
	cacheOnce   *sync.Once
	cacheBlocks *[]outputBlock
}

// Unwrap returns the underlying error that this OopsError wraps.
// This method implements the errors.Wrapper interface.
func (o OopsError) Unwrap() error {
	_ = "STUB: not implemented"

	// toLayer converts the current OopsError into an OopsErrorLayer containing
	// only the attributes set at this specific layer. No chain traversal is performed.
	// Map values are processed the same way as in ToMap: lazy functions are evaluated
	// and pointer values are dereferenced.
	return nil
}

func (o OopsError) toLayer() *OopsErrorLayer { _ = "STUB: not implemented"; return nil }

// Layers returns a slice of all OopsError layers in the error chain,
// from outermost to innermost. Each element represents one wrapping layer
// with its own attributes, allowing callers to inspect or select attributes
// from any layer rather than only the deepest one.
//
// Only OopsError layers are included; non-OopsError errors in the chain
// (e.g. a plain fmt.Errorf or sentinel error at the root) are skipped.
// Use Unwrap() on the innermost layer to access the underlying error.
func (o OopsError) Layers() []*OopsErrorLayer { _ = "STUB: not implemented"; return nil }

// Is implements the errors.Is interface.
//
// OopsError contains non-comparable fields (maps, slices), so the default
// equality check performed by errors.Is would panic at runtime. Identity is
// therefore established via the span ID, which is unique per error instance.
//
// Note: errors.Is is designed for sentinel value matching (e.g. io.EOF).
// To check whether an error in the chain is an OopsError, prefer errors.As
// or oops.AsOops instead.
func (o OopsError) Is(err error) bool { _ = "STUB: not implemented"; return false }

// Error returns the error message without additional context.
// This method implements the error interface.
// If the error wraps another error, it returns "message: wrapped_error".
// Otherwise, it returns just the message.
func (o OopsError) Error() string { _ = "STUB: not implemented"; return "" }

// Code returns the error code from the deepest error in the chain.
// Error codes are machine-readable identifiers that can be used for
// programmatic error handling and cross-service error correlation.
func (o OopsError) Code() any { _ = "STUB: not implemented"; return *new(any) }

func getDeepestErrorCode(err OopsError) any { _ = "STUB: not implemented"; return *new(any) }

// Time returns the timestamp when the error occurred.
// Returns the time from the deepest error in the chain.
func (o OopsError) Time() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// Duration returns the duration associated with the error.
// Returns the duration from the deepest error in the chain.
func (o OopsError) Duration() time.Duration { _ = "STUB: not implemented"; return *new(time.Duration) }

// Domain returns the domain/feature category of the error.
// Returns the domain from the deepest error in the chain.
func (o OopsError) Domain() string { _ = "STUB: not implemented"; return "" }

// Tags returns all unique tags from the error chain.
// Tags are merged from all errors in the chain and deduplicated.
func (o OopsError) Tags() []string { _ = "STUB: not implemented"; return nil }

// reasonable initial capacity for tags

// HasTag checks if the error or any of its wrapped errors contain the specified tag.
// This is useful for conditional error handling based on error categories.
func (o OopsError) HasTag(tag string) bool { _ = "STUB: not implemented"; return false }

// Context returns a flattened key-value context map from the error chain.
// Context from all errors in the chain is merged, with later errors taking precedence.
// Pointer values are dereferenced if DereferencePointers is enabled.
// Lazy evaluation functions are executed to get their values.
func (o OopsError) Context() map[string]any { _ = "STUB: not implemented"; return nil }

// Trace returns the transaction/trace/correlation ID.
// An ID is auto-generated at error creation time if none was set explicitly.
//
// Explicit traces (set via .Trace("id")) always take precedence over
// auto-generated ones, regardless of chain depth. Among traces of the same
// kind, the deepest one in the chain wins.
func (o OopsError) Trace() string { _ = "STUB: not implemented"; return "" }

// getTraceFromChain walks the full error chain and returns the deepest
// explicit trace, falling back to the deepest auto-generated trace.
func getTraceFromChain(err OopsError) string { _ = "STUB: not implemented"; return "" }

// recursive visits outer→inner, so each write overwrites with a deeper value.

// Span returns the current span identifier.
// Unlike other attributes, span returns the current error's span, not the deepest one.
func (o OopsError) Span() string {
	_ = "STUB: not implemented"

	// Hint returns a debugging hint for resolving the error.
	// Returns the hint from the deepest error in the chain.
	return ""
}

func (o OopsError) Hint() string { _ = "STUB: not implemented"; return "" }

// Public returns a user-safe error message.
// Returns the public message from the deepest error in the chain.
func (o OopsError) Public() string { _ = "STUB: not implemented"; return "" }

// Owner returns the name/email of the person/team responsible for handling this error.
// Returns the owner from the deepest error in the chain.
func (o OopsError) Owner() string { _ = "STUB: not implemented"; return "" }

// User returns the user ID and associated user data.
// Returns the user information from the deepest error in the chain.
func (o OopsError) User() (string, map[string]any) { _ = "STUB: not implemented"; return "", nil }

// Tenant returns the tenant ID and associated tenant data.
// Returns the tenant information from the deepest error in the chain.
func (o OopsError) Tenant() (string, map[string]any) { _ = "STUB: not implemented"; return "", nil }

// Request returns the associated HTTP request.
// Returns the request from the deepest error in the chain.
func (o OopsError) Request() *http.Request { _ = "STUB: not implemented"; return nil }

// request returns the internal request tuple with body inclusion flag.
func (o OopsError) request() *lo.Tuple2[*http.Request, bool] { _ = "STUB: not implemented"; return nil }

// Response returns the associated HTTP response.
// Returns the response from the deepest error in the chain.
func (o OopsError) Response() *http.Response { _ = "STUB: not implemented"; return nil }

// response returns the internal response tuple with body inclusion flag.
func (o OopsError) response() *lo.Tuple2[*http.Response, bool] {
	_ = "STUB: not implemented"
	return nil
}

// rawBlocksWithCache returns the filtered frame blocks shared by Stacktrace and Sources.
// When a cache is present the traversal runs at most once; subsequent calls return
// the cached slice directly.
func (o OopsError) rawBlocksWithCache() []outputBlock { _ = "STUB: not implemented"; return nil }

// rawBlocks performs the actual recursive frame traversal and applyFrameSkip filtering.
func (o OopsError) rawBlocks() []outputBlock { _ = "STUB: not implemented"; return nil }

// Stacktrace returns a formatted string representation of the error's stack trace.
// The stack trace shows the call hierarchy leading to the error, excluding
// frames from the Go standard library and this package.
// The stacktrace is basically written from the bottom to the top, in order to dedup frames.
// It support recursive code.
func (o OopsError) Stacktrace() string { _ = "STUB: not implemented"; return "" }

// StackFrames returns the raw stack frames as runtime.Frame objects.
// This is useful for custom stack trace formatting or analysis.
func (o OopsError) StackFrames() []runtime.Frame { _ = "STUB: not implemented"; return nil }

// Sources returns formatted source code fragments around the error location.
// This provides context about the code that caused the error, which is
// particularly useful for debugging. The output includes line numbers and
// highlights the exact line where the error occurred.
func (o OopsError) Sources() string { _ = "STUB: not implemented"; return "" }

// LogValuer returns a slog.Value representation of the error.
// This method implements the slog.LogValuer interface for structured logging.
//
// Deprecated: Use LogValue instead.
func (o OopsError) LogValuer() slog.Value {
	_ = "STUB: not implemented"
	return *

	// LogValue returns a slog.Value representation of the error for structured logging.
	// This method implements the slog.LogValuer interface and provides a flattened
	// representation of the error's context and metadata suitable for logging systems.
	new(slog.Value)
}

func (o OopsError) LogValue() slog.Value {
	_ = "STUB: not implemented" //nolint:gocyclo
	return *new(slog.Value)
}

// if span := o.Span(); span != "" {
// 	attrs = append(attrs, slog.String("span", span))
// }

// ToMap converts the error to a map representation suitable for JSON serialization.
// This method provides a flattened view of all error attributes and is useful
// for logging, debugging, and cross-service error transmission.
func (o OopsError) ToMap() map[string]any {
	_ = "STUB: not implemented" //nolint:gocyclo
	return nil
}

// if span := o.Span(); span != "" {
// 	payload["span"] = span
// }

// MarshalJSON implements the json.Marshaler interface.
// This allows OopsError to be directly serialized to JSON.
func (o OopsError) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// Format implements the fmt.Formatter interface for custom formatting.
// Supports the following format verbs:
// - %v: standard error message
// - %+v: verbose format with stack trace and context
// - %#v: Go syntax representation.
func (o OopsError) Format(s fmt.State, verb rune) { _ = "STUB: not implemented"; return }

// Verbose format with stack trace and context

// Standard format

// formatVerbose returns a detailed string representation of the error
// including all context, stack trace, and source code fragments.
func (o *OopsError) formatVerbose() string {
	_ = "STUB: not implemented" //nolint:gocyclo
	return ""
}

// if span := o.Span(); span != "" {
// 	_, _ = fmt.Fprintf(&output, "Span: %s\n", span)
// }

// formatSummary returns a brief summary of the error for logging.
func (o *OopsError) formatSummary() string { _ = "STUB: not implemented"; return "" }
